name: Run Hello World

on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Debug
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

      - name: Get Stage
        run: echo "The Build stage is ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}"
